# Generated by Django 2.1.4 on 2019-01-03 15:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'stats datum',
                'verbose_name_plural': 'stats data',
            },
        ),
    ]
