# Generated by Django 2.1.4 on 2019-01-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_slug', models.SlugField()),
                ('auth_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.PositiveIntegerField(blank=True, null=True)),
                ('eactivities_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('sold', models.PositiveIntegerField(blank=True, null=True)),
                ('initial', models.PositiveIntegerField(blank=True, null=True)),
                ('currently_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.PositiveIntegerField(blank=True, null=True)),
                ('eactivities_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('sold', models.PositiveIntegerField(blank=True, null=True)),
                ('initial', models.PositiveIntegerField(blank=True, null=True)),
                ('dirty', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icusync.Product')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKUs',
            },
        ),
        migrations.CreateModel(
            name='SKUEntitlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('subscribe_to_mailing_list', models.BooleanField(default=False)),
                ('mailing_list_subscribe_header', models.TextField(blank=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Entitlement')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icusync.SKU')),
            ],
            options={
                'verbose_name': 'SKU entitlement',
                'verbose_name_plural': 'SKU entitlements',
            },
        ),
        migrations.CreateModel(
            name='SKUTicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icusync.SKU')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.TicketType')),
            ],
            options={
                'verbose_name': 'SKU ticket type',
                'verbose_name_plural': 'SKU ticket types',
            },
        ),
    ]
