# Generated by Django 2.1.4 on 2019-01-03 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation', models.CharField(max_length=120)),
                ('film_title', models.CharField(max_length=120)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=256, unique=True)),
                ('last_seen', models.DateTimeField()),
            ],
        ),
    ]
